### ISSUE TITLE
关于bufferlist的一个疑问

### ISSUE THREAD

**Issue by F280319492** [IxaRyo/bluefs-fuse-lite2#1]
https://github.com/IxaRyo/bluefs-fuse-lite2/blob/9fe7d47175e5a4e4558da920cf551323f0f65f3b/src/bufferlist.h#L30-L32
目前实现的bufferlist只能缓存已经读取好的数据？比如将aio的buffer append就不行？

**Comment by IxaRyo** [comment]
是的，bufferlist实际是char数组，ceph中的bufferlist实际太复杂，不打算抽离出来。 
目前是使用bufferlist_nc 进行序列化和反序列化处理。
考虑先完成bluefs的逻辑，后再完成磁盘写入部分（spdk、aio等）

**Comment by F280319492** [comment]
OK，明白了👍
